### ISSUE TITLE
Deletion of _, spaces and - characters

### ISSUE THREAD

**Issue by RamonGilabert** [hyperoslo/NSString-HYPNetworking#1]
When you try to add in the hyp_remoteString or hyp_localString a string that contains one of the characters in the set that you create in the methods: "_- " then it deletes those values and it doesn't add a _. So let's say that you want age_of_person, you enter that as a value, it should say, as a result age_of_person, but the result turns to be ageofperson.

**Comment by 3lvis** [comment]
Oh, I get it! The issue is that we don't do any caching, but you're right. It's a valid use case.

Test:

`[@"age_of_person" hyp_localString]` => `ageOfPerson`

`[@"ageOfPerson" hyp_remoteString]` => `age_of_person`

Returns unexpected results.

**Comment by 3lvis** [comment]
This is working! \o/
