### ISSUE TITLE
Crashes when accessing shared storage

### ISSUE THREAD

**Issue by Jonge** [hyperoslo/NSString-HYPNetworking#12]
I'm using this library with Sync v1.8.0. The app sometimes crashes with the following error:

```
malloc: *** error for object 0x7fc6ca5f9150: double free
*** set a breakpoint in malloc_error_break to debug
```

After setting a breakpoint, I found out that the line responsible for the crash was `[[[HYPNetworkingStringStorage sharedInstance] storage] setObject:result forKey:self];`.

I didn't have these crashes before. I think this commit might have introduced them: https://github.com/hyperoslo/NSString-HYPNetworking/commit/a8319615073a97d48b700b83a6bfd0131664a0e5

I have a suspicion that the dictionary is sometimes being changed from multiple threads (I'm using multiple fetches and syncing at the same time), and therefore it should be made thread safe.

**Comment by 3lvis** [comment]
@Jonge I have an idea on what's going on. I'll try to fix it. (is missing a strong reference)

**Comment by 3lvis** [comment]
@Jonge let me know if this helps https://github.com/hyperoslo/Sync/releases/tag/1.8.1

**Comment by Jonge** [comment]
@3lvis Sure, thanks a lot!

**Comment by Jonge** [comment]
@3lvis Deployed it to production. Today I got a crash:

```
2   NSString_HYPNetworking               0x0000000100e18d88 -[NSString(HYPNetworking) hyp_localString] (NSString+HYPNetworking.m:68)
```

Which translates to this line:

```
NSString *storedResult = [[[HYPNetworkingStringStorage sharedInstance] storage] objectForKey:self];
```

So I guess the locks need to be added to getters as well.

Otherwise everything seems fine. Thanks!

**Comment by 3lvis** [comment]
@Jonge I'll have a look, thanks!
